source "https://rubygems.org"

gemspec

group :development, :test do
  gem "riverqueue", path: "../.."
  gem "standard"
end

group :test do
  gem "rspec-core"
  gem "rspec-expectations"
  gem "simplecov", require: false
end
