module Fnv
  class Hash
    # Calculates the FNV-1 hash for the given
    # item value
    #
    # @param item The item to hash
    # @param size [Integer] the size of the resulting hash
    #
    # @return [Integer] the calculated hash value
    def self.fnv_1: (Object, size: Integer) -> Integer

    # Calculates the FNV-1a hash for the given
    # item value
    #
    # @param item The item to hash
    # @param size [Integer] the size of the resulting hash
    #
    # @return [Integer] the calculated hash value
    def self.fnv_1a: (Object, size: Integer) -> Integer
  end
end